"""Build a non-active BALANCED_STABLE_MICRO V2 candidate profile."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping


def build_micro_profile_candidate(
    *,
    profile_config: Mapping[str, str],
    profile_lines: list[str],
    summary: Mapping[str, Any],
    output_dir: str | Path,
) -> dict[str, Any]:
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    path = output / "balanced_stable_micro_v2_candidate.ini"
    changes: list[str] = []
    values = {str(key).upper(): str(value) for key, value in profile_config.items()}
    if "COOLDOWN_AFTER_LOSS_MINUTES" in values and _can_reduce_cooldown(summary):
        old = _float(values["COOLDOWN_AFTER_LOSS_MINUTES"], 120.0)
        new = max(30.0, old * 0.75)
        values["COOLDOWN_AFTER_LOSS_MINUTES"] = str(int(new) if new.is_integer() else round(new, 2))
        changes.append(f"COOLDOWN_AFTER_LOSS_MINUTES {old:g} -> {new:g}")
    candidate_lines = [
        "; NOT_ACTIVE_RESEARCH_ONLY=true",
        "; Generated by micro-frequency-calibration. Do not use automatically.",
        "NOT_ACTIVE_RESEARCH_ONLY=true",
    ]
    written_keys: set[str] = set()
    if profile_lines:
        for raw in profile_lines:
            if "=" not in raw or raw.strip().startswith(("#", ";")):
                candidate_lines.append(raw)
                continue
            key, _value = raw.split("=", 1)
            canonical = key.strip().upper()
            written_keys.add(canonical)
            candidate_lines.append(f"{key.strip()}={values.get(canonical, _value.strip())}")
    else:
        for key, value in sorted(values.items()):
            written_keys.add(key)
            candidate_lines.append(f"{key}={value}")
    for key, value in {
        "SIGNAL_PROFILE": "BALANCED_STABLE_MICRO_V2_CANDIDATE",
        "BASE_PROFILE": values.get("BASE_PROFILE", "BALANCED_STABLE"),
        "NOT_FOR_DEMO_LIVE": "true",
        "PAPER_ONLY": "true",
        "PAPER_RISK_MULTIPLIER": values.get("PAPER_RISK_MULTIPLIER", "0.1"),
        "MAX_OPEN_PAPER_TRADES": values.get("MAX_OPEN_PAPER_TRADES", "1"),
        "MAX_PAPER_TRADES_PER_DAY": values.get("MAX_PAPER_TRADES_PER_DAY", "2"),
    }.items():
        if key not in written_keys:
            candidate_lines.append(f"{key}={value}")
    if not changes:
        candidate_lines.append("; MANUAL_PROFILE_REVIEW_REQUIRED=true")
    path.write_text("\n".join(candidate_lines) + "\n", encoding="utf-8")
    return {
        "candidate_profile_available": True,
        "candidate_profile_path": str(path),
        "candidate_profile_changes": changes,
        "manual_profile_review_required": not changes,
        "execution_attempted": False,
        "order_send_called": False,
        "order_check_called": False,
    }


def _can_reduce_cooldown(summary: Mapping[str, Any]) -> bool:
    return (
        int(summary.get("cooldown_block_count", 0) or 0) > 0
        and int(summary.get("active_scaled_drawdown_count", 0) or 0) == 0
        and not bool(summary.get("drawdown_active", False))
    )


def _float(value: Any, default: float) -> float:
    try:
        return float(value)
    except Exception:
        return default
