"""Canonical operational state: one halt detector, one paper state, one relaunch gate."""

from .errors import (
    ConfigurationError,
    DataError,
    EvidenceError,
    ExecutionSimulationError,
    InstrumentError,
    OperationalError,
    PaperStateError,
    RiskError,
    TimestampError,
    error_record,
)
from .halt_detector import (
    DEFAULT_DAILY_DRAWDOWN_LIMIT,
    HALT_TOKENS,
    HaltAssessment,
    HaltRecord,
    classify_halt_reason,
    detect_halt,
    halt_kind_of,
    is_halt_event,
)
from .paper_state import PaperState, PaperTradeView, build_paper_state
from .relaunch_gate import BlockingGate, RelaunchAssessment, evaluate_relaunch
from .states import (
    HALT_PRECEDENCE,
    HALT_SEVERITY,
    EvidenceQuality,
    HaltAge,
    HaltKind,
    PaperStateStatus,
    RelaunchDecision,
    Severity,
)

__all__ = [
    "ConfigurationError",
    "DataError",
    "EvidenceError",
    "ExecutionSimulationError",
    "InstrumentError",
    "OperationalError",
    "PaperStateError",
    "RiskError",
    "TimestampError",
    "error_record",
    "DEFAULT_DAILY_DRAWDOWN_LIMIT",
    "HALT_TOKENS",
    "HaltAssessment",
    "HaltRecord",
    "classify_halt_reason",
    "detect_halt",
    "halt_kind_of",
    "is_halt_event",
    "PaperState",
    "PaperTradeView",
    "build_paper_state",
    "BlockingGate",
    "RelaunchAssessment",
    "evaluate_relaunch",
    "HALT_PRECEDENCE",
    "HALT_SEVERITY",
    "EvidenceQuality",
    "HaltAge",
    "HaltKind",
    "PaperStateStatus",
    "RelaunchDecision",
    "Severity",
]
