"""Backtesting and validation tools for AGI_STYLE_FOREX_BOT_MT5."""

from .backtester import (
    Backtester,
    BacktestBatchResult,
    BacktestMetrics,
    BacktestOutcome,
    BacktestSettings,
    CostModel,
    DataQualityReport,
    PromotionGateResult,
    TradeCandidate,
    TradeResult,
    calculate_metrics,
    classify_sample_size,
    classify_strategy_promotion,
    load_historical_csv,
    run_backtest_for_symbols,
    run_strategy_backtest,
)
from .monte_carlo import MonteCarloResult, MonteCarloSimulator, monte_carlo_metrics, run_monte_carlo_report
from .performance_report import PerformanceReportWriter, ReportArtifacts, write_batch_reports, write_reports
from .stress_tester import StressResult, StressTester, run_stress_report
from .validation_report import build_master_validation_report
from .walk_forward_optimizer import (
    RobustScore,
    WalkForwardFold,
    WalkForwardOptimizer,
    WalkForwardResult,
    WalkForwardSettings,
    robust_validation_score,
    run_walk_forward_for_symbols,
)

__all__ = [
    "Backtester",
    "BacktestBatchResult",
    "BacktestMetrics",
    "BacktestOutcome",
    "BacktestSettings",
    "CostModel",
    "DataQualityReport",
    "MonteCarloResult",
    "MonteCarloSimulator",
    "PerformanceReportWriter",
    "PromotionGateResult",
    "ReportArtifacts",
    "RobustScore",
    "StressResult",
    "StressTester",
    "TradeCandidate",
    "TradeResult",
    "WalkForwardFold",
    "WalkForwardOptimizer",
    "WalkForwardResult",
    "WalkForwardSettings",
    "build_master_validation_report",
    "calculate_metrics",
    "classify_sample_size",
    "classify_strategy_promotion",
    "load_historical_csv",
    "monte_carlo_metrics",
    "robust_validation_score",
    "run_backtest_for_symbols",
    "run_monte_carlo_report",
    "run_stress_report",
    "run_strategy_backtest",
    "run_walk_forward_for_symbols",
    "write_batch_reports",
    "write_reports",
]
