"""Compile pure native MQL5 modules with their fixture harnesses as C++ and run them.

This is an emulation on IEEE-754 binary64 with a small, explicit shim for the
MQL5 built-ins these pure modules use (dynamic arrays, strings, Math*). It runs
the same generated assertions the MetaTrader harnesses compile, under a C++
compiler with undefined-behaviour checks and without floating-point
contraction. It is NOT MetaTrader runtime evidence: it does not verify the MQL5
compiler, its string/array implementation, the Strategy Tester, broker data or
execution. Only pure modules with no terminal API are eligible.
"""
from __future__ import annotations

import argparse
from hashlib import sha256
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_VERSION = "native_cpp_emulation_v1"
# (suite, harness, summary record, reviewed static assertion count)
SUITES = (
    ("closed_bars", "ClosedBarWindowHarness.mq5", "NATIVE_CLOSED_BAR_HARNESS", 1103),
    ("core_indicators", "CoreIndicatorsHarness.mq5", "NATIVE_CORE_INDICATORS_HARNESS", 1348),
    ("risk_gate", "RiskGateHarness.mq5", "NATIVE_RISK_GATE_HARNESS", 1433),
)
FLAGS = ("-std=c++17", "-O0", "-ffp-contract=off", "-fno-fast-math", "-fsanitize=undefined",
         "-fno-sanitize-recover=undefined", "-Wall", "-Wno-unused-variable", "-Wno-unused-but-set-variable")
# Terminal, account, symbol, clock, file, network and trading APIs are never shimmed:
# a pure module that needs one fails to compile here instead of being emulated.
FORBIDDEN_PREFIXES = ("Order", "Position", "Symbol", "Account", "Terminal", "File", "Socket", "WebRequest",
                      "Copy", "History", "Chart", "GlobalVariable", "TimeCurrent", "TimeGMT", "TimeLocal",
                      "TimeTradeServer", "MQLInfo", "EventSet", "Sleep")

SHIM = r"""// Generated by scripts/run_native_cpp_emulation.py; emulation shim only.
#include <cfloat>
#include <cmath>
#include <cstdarg>
#include <cstdio>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>
typedef std::string string;
typedef long long datetime;
typedef unsigned long ulong;
template<typename T> struct MqlArray
  {
   std::vector<T> data;
   MqlArray() {}
   explicit MqlArray(int size) : data(size) {}
   // Out-of-range access aborts like the MQL5 runtime's critical error.
   T &operator[](int index) { return data.at(index); }
   const T &operator[](int index) const { return data.at(index); }
  };
template<typename T> int ArraySize(const MqlArray<T> &array) { return (int)array.data.size(); }
template<typename T> int ArrayResize(MqlArray<T> &array,int size) { if(size<0) return -1; array.data.resize(size); return size; }
template<typename T> void ArrayFree(MqlArray<T> &array) { array.data.clear(); array.data.shrink_to_fit(); }
inline bool MathIsValidNumber(double value) { return std::isfinite(value); }
inline double MathAbs(double value) { return std::fabs(value); }
inline double MathRound(double value) { return std::round(value); }
inline double MathFloor(double value) { return std::floor(value); }
inline double MathSqrt(double value) { return std::sqrt(value); }
inline double MathExp(double value) { return std::exp(value); }
inline double MathMin(double left,double right) { return left<right ? left : right; }
inline double MathMax(double left,double right) { return left>right ? left : right; }
inline int StringLen(const string &value) { return (int)value.size(); }
inline int StringTrimLeft(string &value)
  {
   size_t start=value.find_first_not_of(" \t\r\n");
   size_t removed=start==string::npos ? value.size() : start;
   value.erase(0,removed); return (int)removed;
  }
inline int StringTrimRight(string &value)
  {
   size_t end=value.find_last_not_of(" \t\r\n");
   size_t keep=end==string::npos ? 0 : end+1;
   size_t removed=value.size()-keep; value.erase(keep); return (int)removed;
  }
template<typename... Args> void Print(const Args &... args) { (std::cout << ... << args) << '\n'; }
inline void PrintFormat(const char *format,...)
  {
   va_list args; va_start(args,format); std::vprintf(format,args); va_end(args); std::printf("\n");
  }
"""

TRAILER = r"""
int main()
  {
   OnStart();
   std::fflush(stdout);
   return failures==0 ? 0 : 1;
  }
"""

PARAMETER_ARRAY = re.compile(r"\b((?:const\s+)?)([A-Za-z_]\w*)\s*&\s*([A-Za-z_]\w*)\s*\[\s*\]")
DYNAMIC_ARRAY = re.compile(r"\b([A-Za-z_]\w*)\s+([A-Za-z_]\w*)\s*\[\s*\]\s*;")
FIXED_ARRAY = re.compile(r"\b([A-Za-z_]\w*)\s+([A-Za-z_]\w*)\s*\[\s*(\d+)\s*\]\s*;")
DECLARATION_TYPES = re.compile(r"^(?:NativeClosedBar|NativeRiskPosition|double|long|int)$")


def _code_tokens(source):
    clean = re.sub(r'"(?:\\.|[^"\\])*"|//[^\n]*|/\*[\s\S]*?\*/', " ", source)
    return set(re.findall(r"\b[A-Za-z_][A-Za-z_0-9]*\b", clean))


def translate(source: str, name: str) -> str:
    """Rewrite only MQL5 array syntax and drop #property; everything else is C++."""
    forbidden = sorted(token for token in _code_tokens(source) if token.startswith(FORBIDDEN_PREFIXES))
    if forbidden:
        raise ValueError(f"{name} uses terminal APIs and is not a pure module: {', '.join(forbidden[:5])}")
    lines = [line for line in source.splitlines() if not line.lstrip().startswith("#property")]
    text = "\n".join(lines) + "\n"
    text = PARAMETER_ARRAY.sub(lambda m: f"{m.group(1)}MqlArray<{m.group(2)}> &{m.group(3)}", text)

    def dynamic(match):
        if not DECLARATION_TYPES.match(match.group(1)):
            raise ValueError(f"{name}: unsupported dynamic array type {match.group(1)}")
        return f"MqlArray<{match.group(1)}> {match.group(2)};"

    text = DYNAMIC_ARRAY.sub(dynamic, text)

    def fixed(match):
        if not DECLARATION_TYPES.match(match.group(1)):
            return match.group(0)
        return f"MqlArray<{match.group(1)}> {match.group(2)}({match.group(3)});"

    text = FIXED_ARRAY.sub(fixed, text)
    if re.search(r"\bD'", text):
        raise ValueError(f"{name}: MQL5 datetime literals are not supported by the emulation")
    return text


def _includes(source):
    return re.findall(r'^\s*#include\s+(?:"([^"]+)"|<([^>]+)>)', source, re.M)


def stage_suite(harness: str, stage: Path, root: Path = ROOT) -> dict[str, str]:
    """Translate the harness and its whole include graph into a fresh tree."""
    include_root, harness_root = root / "src/mt5/Include", root / "tests/mt5"
    hashes, pending, seen = {}, [harness_root / harness], set()
    while pending:
        path = pending.pop()
        if path in seen:
            continue
        seen.add(path)
        source = path.read_text(encoding="utf-8")
        if path.is_relative_to(include_root):
            relative = Path("include") / path.relative_to(include_root)
        else:
            relative = Path("harness") / path.relative_to(harness_root)
        target = stage / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(translate(source, path.name), encoding="utf-8")
        hashes[path.relative_to(root).as_posix()] = sha256(path.read_bytes()).hexdigest()
        for quoted, angled in _includes(source):
            dependency = (path.parent / quoted) if quoted else (include_root / angled)
            if not dependency.is_file():
                raise FileNotFoundError(dependency)
            pending.append(dependency)
    main = stage / "harness" / ("emulation_" + Path(harness).stem + ".cpp")
    main.write_text(SHIM + f'#include "{harness}"\n' + TRAILER, encoding="utf-8")
    return dict(sorted(hashes.items()))


def run_suite(suite, harness, summary, expected, compiler, workdir, root=ROOT):
    stage = workdir / suite
    result = {"suite": suite, "harness": harness, "expected_checks": expected, "passed": False, "reason": ""}
    try:
        result["source_sha256"] = stage_suite(harness, stage, root)
    except (ValueError, FileNotFoundError) as error:
        result["reason"] = "TRANSLATION_FAILED"
        result["detail"] = str(error)
        return result
    binary = stage / "suite"
    source = stage / "harness" / ("emulation_" + Path(harness).stem + ".cpp")
    compile_run = subprocess.run([compiler, *FLAGS, "-I", str(stage / "include"), "-o", str(binary), str(source)],
                                 capture_output=True, text=True, timeout=600)
    result["compiler_warnings"] = compile_run.stderr.count("warning:")
    if compile_run.returncode != 0:
        result["reason"] = "COMPILE_FAILED"
        result["detail"] = compile_run.stderr[-4000:]
        return result
    run = subprocess.run([str(binary)], capture_output=True, text=True, timeout=600,
                         env={"UBSAN_OPTIONS": "print_stacktrace=1:halt_on_error=1", "PATH": os.environ.get("PATH", "")})
    lines = run.stdout.splitlines()
    failures = [line[len("ASSERTION_FAILED: "):] for line in lines if line.startswith("ASSERTION_FAILED: ")]
    summaries = [line for line in lines if line.startswith(summary + " ")]
    result.update(exit_code=run.returncode, assertion_failures=failures[:100], assertion_failure_count=len(failures),
                  ubsan_report="runtime error" in run.stderr)
    match = re.fullmatch(rf"{summary} checks=(\d+) failures=(\d+)", summaries[0]) if len(summaries) == 1 else None
    if run.returncode != 0 and not failures:
        result["reason"] = "RUNTIME_ABORTED"
        result["detail"] = run.stderr[-4000:]
    elif not match:
        result["reason"] = "SUMMARY_MISSING"
    else:
        result["checks"], result["failures"] = int(match.group(1)), int(match.group(2))
        if result["checks"] != expected:
            result["reason"] = "CHECK_COUNT_MISMATCH"
        elif result["failures"] or failures or run.returncode != 0 or result["ubsan_report"]:
            result["reason"] = "ASSERTION_FAILURES"
        else:
            result["passed"] = True
            result["reason"] = "EMULATED_FIXTURES_PASSED"
    return result


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--compiler", default=shutil.which("g++") or "g++")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--suite", choices=[suite for suite, *_ in SUITES], action="append")
    # A copy of src/mt5/Include and tests/mt5 (e.g. a deliberately mutated one).
    parser.add_argument("--source-root", type=Path, default=ROOT)
    args = parser.parse_args(argv)
    selected = [item for item in SUITES if not args.suite or item[0] in args.suite]
    version = subprocess.run([args.compiler, "--version"], capture_output=True, text=True).stdout.splitlines()[:1]
    with tempfile.TemporaryDirectory(prefix="agi-native-cpp-") as directory:
        results = [run_suite(*item, args.compiler, Path(directory), args.source_root.resolve()) for item in selected]
    evidence = {"schema_version": SCHEMA_VERSION, "scope": "CPP_EMULATION_OF_PURE_NATIVE_MODULES",
        "compiler": version[0] if version else "", "flags": list(FLAGS),
        "passed": all(item["passed"] for item in results), "suites": results,
        "mql5_runtime_verified": False, "execution_authorized": False, "full_pipeline_verified": False,
        "limits": ["Emulates MQL5 arrays, strings and Math* with an explicit C++ shim.",
                   "Does not verify the MQL5 compiler, Strategy Tester, broker data or execution."]}
    payload = json.dumps(evidence, indent=2) + "\n"
    if args.output:
        args.output.write_text(payload, encoding="utf-8")
    for item in results:
        print(f"{item['suite']}: {item['reason']} checks={item.get('checks')} failures={item.get('failures')}")
    return 0 if evidence["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
