"""Write a non-active proposed micro V2 profile."""

from __future__ import annotations

from pathlib import Path
from typing import Any


REQUIRED_MARKERS = {
    "PROFILE_NAME": "BALANCED_STABLE_MICRO_V2_PROPOSED",
    "SIGNAL_PROFILE": "BALANCED_STABLE_MICRO_V2_PROPOSED",
    "PAPER_ONLY": "true",
    "NOT_FOR_DEMO_LIVE": "true",
    "NOT_FOR_LIVE": "true",
    "NOT_ACTIVE_RESEARCH_ONLY": "true",
    "APPROVED_FOR_PAPER_DRY_RUN_ONLY": "false",
    "REQUIRES_STABLE_GATE": "true",
    "REQUIRES_PAPER_RISK_CLEARANCE": "true",
    "REQUIRES_DAILY_RISK_LEDGER": "true",
    "CREATED_FROM": "balanced_stable_micro.ini",
    "SOURCE_PHASE": "FASE_47_CONTROLLED_MICRO_FREQUENCY_PROPOSAL",
    "EXECUTION_ATTEMPTED": "false",
}


def apply_changes(base_values: dict[str, str], changes: list[dict[str, Any]]) -> dict[str, str]:
    proposed = dict(base_values)
    for change in changes:
        key = str(change.get("key", "")).upper()
        if key in proposed:
            proposed[key] = str(change.get("proposed_value", proposed[key]))
    proposed.update(REQUIRED_MARKERS)
    return proposed


def write_proposed_profile(path: str | Path, values: dict[str, str]) -> dict[str, Any]:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = ["; NOT_ACTIVE_RESEARCH_ONLY=true", "; Generated by micro-frequency-proposal. Do not use automatically."]
    lines.extend(f"{key}={values[key]}" for key in sorted(values))
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {
        "proposed_profile_created": True,
        "proposed_profile_path": str(output),
        "execution_attempted": False,
        "order_send_called": False,
        "order_check_called": False,
    }
